### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy#23]
Install instructions for both README.md and Install page on http://galaxy.ooo

- [x] Install instructions galaxypi/galaxy repository README.md
- [x] Install instructions for http://galaxy.ooo install page

@faddat will create the first round of Install Instructions by posing on the galaxypi/galaxy repository README.md by no later than the morning of Sat, Jul 21, 2018. Could be sooner if @faddat happens to get some free time.

**Comment by faddat** [comment]
It should be tomorrow.

**Comment by faddat** [comment]
New install instructions should include a link to `#node-operators` on Slack, and should encourage the user to create a wallet address and have us send some coins to it.

**Comment by guylepage3** [comment]
>Lastly, do we want to stay with Slack?

Is this for the install instructions?

**Comment by faddat** [comment]
Yes, totally.  Because the install instructions should contain a link to the node-operators channel.

**Comment by faddat** [comment]
The reason it's here is specifically:  

I cannot find a way to create a link to `#node-operators'.  

The best thing that could possibly happen after a user follows the testnet setup instructions is that they join that channel and have one of us send them tokens.

**Comment by faddat** [comment]
Reviewing our current readme:

Right now, we have "join the testnet"

and then we have "single line install for mac"

For TN 4, we can unify around @vsund 's design that changes our binary names and adds a seeds file and can be mostly seen in the development branch.  

Instead of starting a 3.5 (with new directions but no unification from @vsund 's code), I'm going to start TN4.  

Without it, there's no way to write the install instructions because I won't know the node ID, node IP address, etc.  

Since I've done this a few times now, probably shouldn't take so long to start the new testnet and be able to use @vsund 's setup.

**Comment by guylepage3** [comment]
Let's skip the node-operators channel integration for now. We will be opening up a Discourse Forum after this big initial goal is met. :)

**Comment by guylepage3** [comment]
Hey @faddat can we close this out?
